# The main config file for your Jekyll template

# Site settings
title: Sameer Mehra               # used for the html title of every page
desc: >
  Personal website for Sameer 'Sammy' Mehra. Thanks for stopping
  by!

url: http://sameermehra.com      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: sammysignal@gmail.com
author: Sameer Mehra
linkedin_username: sameer-mehra
github_username: sammysignal
github_source: sammysignal.github.io

# Put your ga tracking code below
google_analytics: 'UA-83124629-1'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/blog/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: About
    url: /about/
    desc: About Sameer
  - title: Projects
    url: /projects/
    desc: Personal Projects
  - title: Music
    url: /music/
    desc: Music
  # - title: Blog
  #   url: /blog/
  #   desc: Blog
  # - title: Work
  #   url: /work/
  #   desc: Work Experience


# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

